apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: docker.io/aturytsia/demo-app:7fd52f2dc8ce1aed0cfcc85c78cd5d00c108edbf
          imagePullPolicy: Always
